import { Link } from "react-router-dom";
import BlogLayout from "@/components/BlogLayout";
import ArchitectureGraphView from "@/components/architecture/ArchitectureGraph";
import architectureJson from "@/data/architecture.json";
import type { ArchitectureGraph } from "@/components/architecture/types";

const graph = architectureJson as unknown as ArchitectureGraph;

const ArchitecturePage = () => {
  return (
    <BlogLayout>
      <div className="mx-auto w-full max-w-[1400px] px-3 py-4">
        <ArchitectureGraphView graph={graph} />

        <section className="mx-auto mt-10 max-w-3xl px-2 text-sm leading-relaxed text-brand-20">
          <p className="text-xs italic text-muted-foreground">
            generated by codearchview {graph.meta.toolVersion}
            {graph.meta.commit ? ` from commit ${graph.meta.commit}` : ""}.
          </p>
          <Link
            to="/blog/codearchview"
            className="group mt-4 inline-flex items-baseline gap-2 text-lg text-brand hover:text-brand-25"
          >
            <h2 className="underline decoration-brand-70 decoration-1 underline-offset-4 group-hover:decoration-brand">
              what is this?
            </h2>
            <span className="text-sm text-muted-foreground transition-transform group-hover:translate-x-0.5">
              →
            </span>
          </Link>
        </section>
      </div>
    </BlogLayout>
  );
};

export default ArchitecturePage;
